### ISSUE TITLE
Top navigation bar display issue

### ISSUE THREAD

**Issue by tasnimAlam** [Shrek53/react-native-boilarplate-app#2]
Top navigation bar displays behind phone status bar.

**Screenshots**
https://ibb.co/sVkhXTX

**Smartphone**
 - Device: Xiaomi A1
 - OS: Android 8.1

**Comment by Shrek53** [comment]
This issue should be resolved now. Please let me know if it works for you.

**Comment by tasnimAlam** [comment]
Still tab bar is showing behind the status bar. 

Screenshot: https://m.imgur.com/gallery/2TiqXwM
